version: 1
title: Home
wallpaper: /wallpapers/landscape.webp
adminGroups: [dashboard-admins]
access:
  allowAdmin: true
  anyOf:
    - allOf: [dashboard-users]
apps:
  - id: jellyfin
    name: Jellyfin
    description: Your movies, series and music
    href: https://jellyfin.example.com
    icon: play
    iconPath: /icons/jellyfin.svg
    color: "#181526"
    category: Media
    access:
      allowAdmin: true
      anyOf:
        - allOf: [dashboard-users, app-jellyfin]
  - id: immich
    name: Immich
    description: A home for your photos and videos
    href: https://immich.example.com
    icon: link
    iconPath: /icons/immich.svg
    color: "#edf1f5"
    category: Photos
    access:
      allowAdmin: true
      anyOf:
        - allOf: [dashboard-users, app-immich]
  - id: gitea
    name: Gitea
    description: A place for your code and projects
    href: https://gitea.example.com
    icon: link
    iconPath: /icons/gitea.svg
    color: "#edf1f5"
    category: Development
    access:
      allowAdmin: true
